# Generated by Django 4.0 on 2021-12-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Haber', 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'Haber Kategori', 'verbose_name_plural': 'Haber Kategorileri'},
        ),
        migrations.AddField(
            model_name='news',
            name='image_address',
            field=models.FileField(blank=True, help_text='Maksimum 5MB resim seçiniz', null=True, upload_to='', verbose_name='Haber Resmi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='detail',
            field=models.TextField(verbose_name='Haber Detayı'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscategory', verbose_name='Haber Kategorisi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='desc',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Başlık'),
        ),
    ]
