# Generated by Django 4.0 on 2021-12-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_newscategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image_address',
            field=models.FileField(blank=True, help_text='Maksimum 5MB resim seçiniz', null=True, upload_to='images', verbose_name='Haber Resmi'),
        ),
    ]
